### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Telegram.Bot, Version=13.2.1.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by yunfandev** [stdray/Seq.App.Telegram#3]
I install the latest version v.0.0.1.9

When I try to send an event to telegram it failed with the following error
```
System.IO.FileNotFoundException: Could not load file or assembly 'Telegram.Bot, Version=13.2.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Telegram.Bot, Version=13.2.1.0, Culture=neutral, PublicKeyToken=null'
   at Seq.App.Telegram.TelegramReactor.On(Event`1 evt)
   at Seq.Apps.GenericHost.AppHost.SendTypedEventAsync(String clef)

```

**Comment by yunfandev** [comment]
I run the latest docker version seq.

I found this problem is caused by the absence of  Telegram.Bot.dll in the net452 directory.

**Comment by stdray** [comment]
@yunfandev thanx for contrubution. also i've created .netstandart package which compatible with Seq5.1+. You may try to use it (nuget version 5+).
