### ISSUE TITLE
Misleading exception about invalid token format due to lack of support for 64-bit bot IDs

### ISSUE THREAD

**Issue by rpendleton** [stdray/Seq.App.Telegram#9]
Within the past few months, Telegram has started assigning users and bots 64-bit IDs. Newer versions of the Telegram API support these IDs (version 17 and newer I believe), but since this project is using an older version, newly created bots can't be used.

Attempting to use a token for a new bot with the most recent release of Seq.App.Telegram results in the following misleading exception being thrown by the Telegram API:
> Unhandled Exception: System.ArgumentException: Invalid format.
> A valid token looks like "1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy"

I was able to fix this by updating the Telegram API to the latest version.

I would have submitted a PR for that change, however, it seems the update also removed the proxy constructor parameter for the Telegram client. I figure there must be a new way of configuring the proxy (perhaps on the HttpClient itself?), but since I didn't need the proxy, I didn't look into it much further and just stripped out the proxy-related code so that I could continue with my configuration of Seq.

**Comment by chris-metz** [comment]
Thank you for pointing this out! I had the same issue and by using an old bot (luckily having one) I could it get working.

Anyways, the plugin being updated to work with the new API would be great, since as already stated by @rpendleton newly created bots can't be used anymore.

**Comment by stdray** [comment]
@rpendleton @chris-metz  Telegram api updated, please check latest version

 @chris-metz Thank you for PR!

**Comment by prodigy** [comment]
Actually I did submit the PR because I ran into this issue myself. While I was at it I fixed the Proxy stuff.

I think the issue can be closed?

**Comment by rpendleton** [comment]
I just updated to the latest version of this app and can confirm that #10 fixed the issue with 64-bit bot IDs.

(I'm sorry about the delay in confirming. I'm not sure how I missed the replies from earlier this year...)
